<MDG.Selections model="C:\Users\broth\Dropbox\work\Method\EA method\3.1\Model\DigitalArchitectureFramework.eapx">
	<Technology id="DAF" name="DigitalArchitectureFramework" version="5.0 Alpha21" notes="the Digital Architecture Framework (DAF) is an UML profile covering Enterprise Architecture, Business Analysis and Solution Architecture. It derives from TOGAF, BizBOZ, RUP and OpenUP connecting those standards in a tailored, consistent language." filename="C:\Users\broth\Dropbox\work\Method\EA method\3.1\technology\DAF.xml" infoURI="github.com/FreeTAKTeam/DigitalArchitectureFramework" supportURI="borthercorvo@gmail.com" icon="C:\Users\broth\Dropbox\work\Method\EA method\3.1\Icons\bmp\dGoal.bmp" logo="C:\Users\broth\Dropbox\work\Method\EA method\3.1\deltaLogo.bmp"/>
	<Profiles directory="C:\Users\\broth\Dropbox\work\Method\EA method\3.1\profile" files="DAFProfile.xml"/>
	<Patterns directory="C:\Users\Broth\Dropbox\work\Method\EA method\3.1\patterns" files=""/>
	<TagVals tags="Alternatives,BizCriticality,BizSatisfaction,CapabilityLevel,Cost,DetailedDescription,EstimatedEffort,finishDate,Impacted Capability,InitiativeDuration,ITSatisfaction,Justification,LastStandardReviewDate,Likehood,Logical Application to Capability,NextStandardReviewDate,Owner,PrincipleMeasurement,Priority,Rank,RelatedDecisions,RelatedProgram,RetireDate,Risk,Severity,Source,Stakeholder,StandardCreationDate,startDate,URL Tagged Value"/>
	<Images images="798351267,648323684,1625952202,1571734840,693912373,1641341341,454260797,1389199861,1333654490,259574216,291025587,666889450,653694403,559442057,605262724,1378408857,2055865375,920864302,1839069948,1882729560,999120925"/>
	<DiagramProfile directory="C:\Users\Broth\Dropbox\work\Method\EA method\3.1\Diagrams" files="DAF_BusinessArchitectureDiagrams.xml,DAF_EnterpriseArchitectureDiagrams.xml,DAF_SolutionArchitectureDiagrams.xml"/>
	<UIToolboxes directory="C:\Users\broth\Dropbox\work\Method\EA method\3.1\toolboxes" files="DAF_Application_Architecture_TB.xml,DAF_Business_Aanalysis_TB.xml,DAF_Business_Architecture_TB.xml,DAF_Data_Architecture_TB.xml,DAF_Requirements_TB.xml,DAF_TechnologyArchitecture.xml,DAFToolbox.xml"/>
	<ModelSearches2/>
	<ModelTemplates>
		<Model name="DAF Catalog Structure" description="" location="C:\Users\broth\Dropbox\work\Method\EA method\3.1\Repository Structure\DAFCatalogs.xml" default="yes" icon="34" filter="" isFramework="false"/>
		<Model name="DAF component" description="a structure suited for generation of a digital Py component" location="C:\tmp\DigPyComponentModelWizardTemplate.xml" default="yes" icon="34" filter="" isFramework="false"/>
	</ModelTemplates>
</MDG.Selections>